<?php

declare(strict_types=1);

namespace Sidetours\Compass\Cli;

use Sidetours\Compass\Engine\Configuration;
use Sidetours\Compass\Engine\IgnoreList;
use Sidetours\Compass\Engine\Runner;
use Symfony\Component\Console\Attribute\AsCommand;
use Symfony\Component\Console\Command\Command;
use Symfony\Component\Console\Input\InputInterface;
use Symfony\Component\Console\Input\InputOption;
use Symfony\Component\Console\Output\OutputInterface;

#[AsCommand(name: 'baseline', description: 'Snapshot current violations into the configured baseline file.')]
final class BaselineCommand extends Command
{
    public function __construct(private readonly string $projectRoot)
    {
        parent::__construct();
    }

    protected function configure(): void
    {
        $this->addOption('config', 'c', InputOption::VALUE_REQUIRED, 'Path to configuration file', 'compass.yaml');
    }

    protected function execute(InputInterface $input, OutputInterface $output): int
    {
        $configFile = $this->resolveConfigPath((string) $input->getOption('config'));
        $config = Configuration::load($configFile, $this->projectRoot);

        if ($config->baseline === null) {
            $output->writeln('<error>No "baseline" path configured in compass.yaml — set one before generating a baseline.</error>');

            return 2;
        }

        $emptyIgnoreList = new IgnoreList($config->ignore, [], $config->projectRoot);
        $result = (new Runner($config, $emptyIgnoreList))->run();

        $fingerprints = array_values(array_unique(array_map(
            static fn ($v) => $v->fingerprint(),
            $result->violations,
        )));
        sort($fingerprints);

        $contents = "<?php\n\ndeclare(strict_types=1);\n\n// Auto-generated by compass baseline. Do not edit by hand.\n\nreturn ".var_export($fingerprints, true).";\n";

        $dir = dirname($config->baseline);
        if (! is_dir($dir) && ! @mkdir($dir, 0775, true) && ! is_dir($dir)) {
            $output->writeln(sprintf('<error>Could not create baseline directory: %s</error>', $dir));

            return 2;
        }
        file_put_contents($config->baseline, $contents);

        $output->writeln(sprintf(
            '<info>Baseline written: %s</info> (%d unique violation fingerprint(s) recorded).',
            $config->baseline,
            count($fingerprints),
        ));

        return 0;
    }

    private function resolveConfigPath(string $path): string
    {
        if ($path !== '' && ($path[0] === '/' || preg_match('#^[A-Za-z]:[\\\\/]#', $path) === 1)) {
            return $path;
        }

        return rtrim($this->projectRoot, '/').'/'.$path;
    }
}
